### ISSUE TITLE
the ion navbar button is not clickable 

### ISSUE THREAD

**Issue by lilian131** [ionicfirebaseapp/ionic-3-restaurantapp#2]
there is something up on the ion-navbar, it make impossible to click on it this is not the title

![capture d ecran 2018-12-10 a 11 56 24](https://user-images.githubusercontent.com/20966587/49728932-19e3a780-fc85-11e8-9d6f-b31cfed63d4f.png)

![capture d ecran 2018-12-10 a 11 33 06](https://user-images.githubusercontent.com/20966587/49728885-00daf680-fc85-11e8-894a-d1ea4ab5e706.png)

I wanted to put my buttons down to avoid this issue but in other ios phone this bar is at the same place that's why I've made it very big 
event the click event of window does not give me result

**Comment by PietechSolution** [comment]
Please update the app and it will work and if still issue let us know, Ionic 3 version we going to make open-source now so everyone can download and use them.

**Comment by lilian131** [comment]
I updated to ionic 4 and it happen too, this was an issue with  **statusBar.overlaysWebView**  what I have made to make it work is : 
```     
if(this._plt.is('android')) {

       this._statusBar.overlaysWebView(false);

} else if(this._plt.is('ios')){

       this._statusBar.overlaysWebView(true);

}
```
